### PR TITLE
Fix https complaints

### PR DESCRIPTION
**Pull request by taoyao-rh**
There is no complaints in firefox brower.
By Changing some image sources to secure source, downloading some js file from insecure site into local directory.

### CODE REVIEW

**Review by rsearls — CHANGES_REQUESTED** [review]
The code in buttons.js is displayed as 1 long line.   Is it possible to format it into separate lines?

Your code changes look good.  In your comments I suggest changing the phrase  ' don't works  ' to   ' doesn't work '.    Also change ' ty ' to ' try '.

**Comment by taoyao-rh** [comment]
Reformat the buttons.js and modify the comments.

**Review by asoldano — CHANGES_REQUESTED** [review]
Thanks @taoyao-rh , I agree with the idea of storing locally resources that are giving issues with https. Is there a reason why only some of the css needed to be pulled locally?
Btw, I suggest comparing the resulting website (just point a browser to the local index.html) before and after the changes. I'm seeing some differences, which make me think there could be something wrong with css and/or js. I'm attaching two screenshots in a minute. Thanks

**Comment by asoldano** [comment]
Before this PR changes

After this PR changes

**Comment by taoyao-rh** [comment]
The issue is caused by the wrong path of local css and js files. I've changed them and checked the pages.

**Comment by taoyao-rh** [comment]
The reason why I just download some of the css or js files is that I only need to modify the css/js containing unsecure source. If the source of unsecure css/js has secure alternative, I just change it to https source.

**Comment by asoldano** [comment]
Out of date, closing

**Pull request closed without merging**
